<?php

/**
 * @file
 * A Feeds framework used to create extensible parsers.
 */

// Ludwig module integration.
if (\Drupal::hasService('ludwig.require_once')) {
  $ludwig_require_once = \Drupal::service('ludwig.require_once');
  $ludwig_require_once->requireOnce('mtdowling/jmespath.php', 'src/JmesPath.php', dirname(__FILE__));
  $ludwig_require_once->requireOnce('gravitypdf/querypath', 'src/qp_functions.php', dirname(__FILE__));
}
