block.settings.entity_block:*:
  type: block_settings
  label: 'Entity Block'
  mapping:
    entity:
      type: string
      label: 'Entity'
    view_mode:
      type: machine_name
      label: 'View mode'